sudo: false

matrix:
  include:
    - rvm: 2.5.0
      env:
        - MONGOID_VERSION=7.0
      before_script:
        - bundle exec danger
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=6.0
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=5.0
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=4.0
    - rvm: 2.2
      env:
        - MONGOID_VERSION=3.1.0
    - rvm: 2.1
      env:
        - MONGOID_VERSION=3.0.0

services: mongodb

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
